[package]
name = "cw22"
version = "0.1.0"
authors = ["ThienLK1@aura-nw"]
edition = "2021"
description = "Definition and types for the CosmWasm-22 interface"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[dependencies]
cosmwasm-schema = "1.0.0"
cosmwasm-std = { version = "1.0.0", default-features = false }
cw-storage-plus = "0.16.0"
schemars = "0.8.1"
serde = { version = "1.0.0", default-features = false, features = ["derive"] }
semver = "1.0.14"
thiserror = { version = "1.0.23" }
