[package]
name = "easy-addr"
version.workspace = true
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
cosmwasm-std = { workspace = true }
proc-macro2 = "1"
quote = "1"
syn = { version = "1.0.6", features = ["full", "printing", "extra-traits"] }
