name: checks

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [created]

jobs:
  contract_cw1_subkeys:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts/cw1-subkeys
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: cw1-subkeys-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.76.0
      - run: cargo unit-test --locked
        env:
          RUST_BACKTRACE: 1
      - run: cargo schema --locked

  contract_cw1_whitelist:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts/cw1-whitelist
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: cw1-whitelist-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.76.0
      - run: cargo unit-test --locked
        env:
          RUST_BACKTRACE: 1
      - run: cargo schema --locked

  contract_cw3_fixed_multisig:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts/cw3-fixed-multisig
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: cw3-fixed-multisig-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.76.0
      - run: cargo unit-test --locked
        env:
          RUST_BACKTRACE: 1
      - run: cargo schema --locked

  contract_cw3_flex_multisig:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts/cw3-flex-multisig
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: cw3-flex-multisig-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.76.0
      - run: cargo unit-test --locked
        env:
          RUST_BACKTRACE: 1
      - run: cargo schema --locked

  contract_cw4_group:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts/cw4-group
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: cw4-group-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.76.0
      - run: cargo unit-test --locked
        env:
          RUST_BACKTRACE: 1
      - run: cargo schema --locked

